"""The main window of the application, orchestrating all UI and hardware components.

This module defines the `MainWindow` class, which serves as the primary container
for the entire graphical user interface. Its responsibilities include:
-   Constructing the main UI layout, including camera panels, control tabs,
    menus, and the status bar.
-   Managing the lifecycle of hardware objects, such as the CT400 device and
    Vimba cameras.
-   Orchestrating the "lazy initialization" of hardware on background threads
    to keep the UI responsive on startup.
-   Connecting signals from hardware and worker objects to slots in the UI
    widgets to update the display.
-   Providing top-level application actions, such as connecting/disconnecting
    instruments and showing dialogs.
-   Coordinating a graceful shutdown of all hardware and threads when the
    application closes.
"""

from __future__ import annotations

import logging
import sys
from enum import Enum, auto

from PySide6 import QtGui, QtWidgets
from PySide6.QtCore import QObject, QRunnable, QSize, Qt, QThreadPool, QTimer, Signal, Slot
from PySide6.QtGui import QAction, QFont, QIcon
from PySide6.QtWidgets import (
    QApplication,
    QFrame,
    QHBoxLayout,
    QLabel,
    QMainWindow,
    QMenu,
    QMessageBox,
    QSizePolicy,
    QSplitter,
    QStatusBar,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from app_settings import AppSettings
from config_model import AppConfig, CameraConfig
from hardware.ct400_init_worker import CT400InitWorker
from hardware.dummy_ct400 import DummyCT400
from hardware.piezo import PiezoController
from hardware.piezo_init_worker import PiezoInitWorker
from logic.task_runner import TaskRunner
from ui.alignment_panel import AlignmentPanel
from ui.discovery_dialog import CameraDiscoveryDialog

try:
    # This file is generated by pyside6-rcc and contains compiled resources
    import resources.resources_rc as resources_rc  # noqa: F401
except ImportError:
    # This warning is helpful for developers running the app without compiling resources
    print(
        "Warning: Compiled resource file (resources_rc.py) not found. Icons might be missing.",
        file=sys.stderr,
    )

from hardware.camera import VIMBA_AVAILABLE, VimbaCam, VmbCameraError, VmbSystem, VmbSystemError
from hardware.camera_init_worker import CameraInitWorker
from hardware.camera_recovery_worker import CameraRecoveryWorker
from hardware.ct400 import CT400
from hardware.ct400_types import Enable, LaserInput
from hardware.interfaces import AbstractCT400
from hardware.simulated_camera import SimulatedCamera
from ui.camera_widgets import CameraPanel
from ui.constants import (
    ID_CT400_STATUS_LABEL,
    MSG_CAMERA_CONNECTING,
    MSG_CAMERA_FAILED,
    MSG_CAMERA_WAITING,
    PROP_STATUS,
)
from ui.control_panel import (
    CT400ConnectionWorker,
    CT400ControlPanel,
    HistogramControlPanel,
    ScanSettings,
)
from ui.plot_widgets import HistogramWidget, PlotWidget

logger = logging.getLogger("LabApp.main_window")


class PiezoConnectionSignals(QObject):
    """Signals for the PiezoConnectionWorker."""

    connection_succeeded = Signal(str)  # side: "left" or "right"
    disconnection_succeeded = Signal(str)  # side
    connection_failed = Signal(str, str)  # side, error_message


class PiezoConnectionWorker(QRunnable):
    """A QRunnable to handle connecting/disconnecting a Piezo in the thread pool."""

    def __init__(self, piezo: PiezoController, side: str, port: str, connect: bool):
        super().__init__()
        self.piezo = piezo
        self.side = side
        self.port = port
        self.do_connect = connect
        self.signals = PiezoConnectionSignals()

    @Slot()
    def run(self):
        try:
            if self.do_connect:
                self.piezo.connect(self.port)
                self.signals.connection_succeeded.emit(self.side)
            else:
                self.piezo.disconnect()
                self.signals.disconnection_succeeded.emit(self.side)
        except Exception as e:
            logger.error(f"Piezo {self.side} operation failed: {e}", exc_info=True)
            self.signals.connection_failed.emit(self.side, str(e))


class CT400Status(Enum):
    """Defines the possible connection states for the CT400 device."""

    CONNECTED = auto()
    DISCONNECTED = auto()
    CONNECTING = auto()
    DISCONNECTING = auto()
    ERROR = auto()
    UNAVAILABLE = auto()
    UNKNOWN = auto()


class CT400OperationState(Enum):
    """Exclusive application owner of the shared CT400 handle."""

    IDLE = auto()
    CONNECTING = auto()
    DISCONNECTING = auto()
    SCANNING = auto()
    MONITORING = auto()
    ALIGNMENT = auto()


class MainWindow(QMainWindow):
    """The main application window.

    This class builds the user interface, manages hardware initialization and
    cleanup, and connects all the components of the application.

    Attributes:
        config (AppConfig): The validated application configuration object.
        cameras (list[VimbaCam]): A list of successfully initialized camera objects.
        camera_panels (dict[str, CameraPanel]): A dictionary mapping camera
            identifiers to their corresponding UI panel widgets.
        ct400_device (AbstractCT400 | None): The active CT400 device instance,
            which could be a real or dummy implementation.
    """

    _ct400_init_task_finished = Signal(object)
    _piezo_init_task_finished = Signal(object)
    _init_task_thread_finished = Signal(object)
    _camera_recovery_thread_finished = Signal(str, object)

    def __init__(self, config: AppConfig, parent=None, settings: AppSettings | None = None):
        """Initializes the MainWindow.

        Sets up the main UI components and defers the slow hardware
        initialization to a later stage to ensure the window appears quickly.

        Args:
            config: The validated AppConfig object containing all startup settings.
            parent: The parent widget, typically None for the main window.
        """
        super().__init__(parent)
        self.config = config
        self.settings = settings if settings is not None else AppSettings()
        logger.info("Initializing MainWindow...")
        # --- Member variable initialization ---
        self.cameras: list[VimbaCam] = []
        self.camera_panels: dict[str, CameraPanel] = {}
        self._init_tasks: set[TaskRunner] = set()
        self._camera_recovery_tasks: dict[str, TaskRunner] = {}

        # --- CT400 and Piezo hardware will be None until workers finish ---
        self.ct400_device: AbstractCT400 | None = None
        self.piezo_left: PiezoController | None = None
        self.piezo_right: PiezoController | None = None

        # --- CT400 Worker ---
        self.ct400_task: TaskRunner | None = None

        # --- Piezo Worker ---
        self.piezo_task: TaskRunner | None = None

        self.shared_scan_settings = ScanSettings()
        self.vmb_instance: VmbSystem | None = None
        self.is_ct400_connected_state: bool = False
        self._ct400_connection_configured: bool = False
        self._ct400_operation_state = CT400OperationState.IDLE
        self._pending_ct400_operation_close: bool = False
        self._pending_init_close: bool = False
        self._pending_camera_lifecycle_close: bool = False
        self._pending_piezo_operation_close: bool = False
        self._piezo_operations_in_flight: set[str] = set()
        self._ct400_error_reset_timer = QTimer(self)
        self._ct400_error_reset_timer.setSingleShot(True)
        self._ct400_error_reset_timer.timeout.connect(self._reset_ct400_error_visuals)
        self.camera_control_actions: dict[str, QAction] = {}
        self.cameras_menu: QMenu | None = None

        self.piezo_connection_succeeded.connect(self._on_piezo_connection_success)
        self.piezo_connection_failed.connect(self._on_piezo_connection_failed)

        # --- UI and deferred initialization ---
        self._init_ui()
        self._restore_ui_preferences()
        self._load_defaults_from_config()
        self._connect_signals()
        self._ct400_init_task_finished.connect(self._on_ct400_init_task_finished)
        self._piezo_init_task_finished.connect(self._on_piezo_init_task_finished)
        self._init_task_thread_finished.connect(self._on_init_task_thread_finished)
        self._camera_recovery_thread_finished.connect(self._on_camera_recovery_thread_finished)

        # Start slow hardware initializations after the main event loop has started.
        # This ensures the GUI is responsive immediately upon launch.
        QTimer.singleShot(100, self._begin_lazy_init)
        logger.info("MainWindow __init__ complete. Hardware initialization deferred.")

    def _restore_ui_preferences(self) -> None:
        """Apply stored presentation preferences after all UI widgets exist."""
        saved_geometry = self.settings.geometry()
        if saved_geometry is not None:
            self.restoreGeometry(saved_geometry)
        saved_sizes = self.settings.splitter_sizes(self.main_splitter.count())
        if saved_sizes is not None:
            self.main_splitter.setSizes(saved_sizes)
        self.tab_widget.setCurrentIndex(
            self.settings.active_tab(self.tab_widget.count(), self.tab_widget.currentIndex())
        )
        saved_detectors = set(self.settings.scan_detectors())
        for detector, checkbox in self.control_panel.scan_detector_cbs.items():
            checkbox.setChecked(detector.value in saved_detectors)

    piezo_connection_succeeded = Signal(str)
    piezo_connection_failed = Signal(str, str)

    @Slot(str)
    def connect_piezo(self, side: str):
        """Connects or disconnects a piezo controller on a worker thread."""
        if self._pending_piezo_operation_close:
            logger.info("Ignoring %s piezo operation while application close is pending.", side)
            return
        if side not in {"left", "right"} or side in self._piezo_operations_in_flight:
            return
        if self._alignment_hardware_transition_blocked():
            logger.info("Ignoring %s piezo operation while alignment owns the hardware.", side)
            return
        if side == "left":
            piezo = self.piezo_left
            port = self.config.instruments.piezo_left_serial
        else:
            piezo = self.piezo_right
            port = self.config.instruments.piezo_right_serial

        if not piezo:
            logger.error(f"Cannot connect {side} piezo: object is None.")
            return

        do_connect = not piezo.is_connected()

        worker = PiezoConnectionWorker(piezo, side, port, do_connect)

        # Connect signals to the main thread's *slots*
        worker.signals.connection_succeeded.connect(self.piezo_connection_succeeded)
        worker.signals.disconnection_succeeded.connect(self._on_piezo_disconnection_success)
        worker.signals.connection_failed.connect(self.piezo_connection_failed)

        # Reserve the controller before dispatch so Refresh cannot replace it.
        self._piezo_operations_in_flight.add(side)
        self._update_piezo_action(side)
        if not do_connect:
            self._sync_alignment_hardware()

        QThreadPool.globalInstance().start(worker)

    def _update_piezo_action(self, side: str):
        """Render the action from the current controller and operation state."""
        action = self.piezo_connect_left_action if side == "left" else self.piezo_connect_right_action
        piezo = self.piezo_left if side == "left" else self.piezo_right
        title = side.capitalize()
        if side in self._piezo_operations_in_flight:
            action.setText(f"{'Disconnecting' if piezo and piezo.is_connected() else 'Connecting'} {title}...")
            action.setEnabled(False)
        elif piezo is None:
            action.setText(f"{title} Piezo (Not Found)")
            action.setEnabled(False)
        else:
            connected = piezo.is_connected()
            action.setText(f"{'Disconnect' if connected else 'Connect'} {title} Piezo")
            action.setEnabled(True)

    def _alignment_hardware_transition_blocked(self) -> bool:
        panel = getattr(self, "alignment_tab", None)
        return bool(
            self._ct400_operation_state is CT400OperationState.ALIGNMENT
            or (panel is not None and (panel._active_mode is not None or panel._ct400_operation_state == "ALIGNMENT"))
        )

    def _sync_alignment_hardware(self):
        """Keep the alignment panel bound only to currently usable hardware."""
        panel = getattr(self, "alignment_tab", None)
        if panel is None:
            return
        if self._alignment_hardware_transition_blocked():
            return
        ready = (
            self.ct400_device is not None
            and self.piezo_left is not None
            and self.piezo_right is not None
            and self.piezo_left.is_connected()
            and self.piezo_right.is_connected()
            and not self._piezo_operations_in_flight
            and not self._pending_piezo_operation_close
            and not self._alignment_hardware_transition_blocked()
        )
        if ready:
            panel.set_hardware(self.ct400_device, self.piezo_left, self.piezo_right)
        else:
            panel.clear_hardware()

    @Slot(str)
    def _on_piezo_connection_success(self, side: str):
        logger.info(f"{side.capitalize()} Piezo connected successfully.")
        self._complete_piezo_operation(side)
        self.statusBar().showMessage(f"{side.capitalize()} Piezo connected.", 3000)

    @Slot(str)
    def _on_piezo_disconnection_success(self, side: str):
        logger.info(f"{side.capitalize()} Piezo disconnected.")
        self._complete_piezo_operation(side)
        self.statusBar().showMessage(f"{side.capitalize()} Piezo disconnected.", 3000)

    @Slot(str, str)
    def _on_piezo_connection_failed(self, side: str, error_message: str):
        logger.error(f"Failed to connect {side} piezo: {error_message}")
        self._complete_piezo_operation(side)
        QMessageBox.critical(self, f"{side.capitalize()} Piezo Error", f"Operation failed: {error_message}")

    def _complete_piezo_operation(self, side: str) -> bool:
        """Release one side's operation ownership and refresh dependent UI."""
        was_in_flight = side in self._piezo_operations_in_flight
        if was_in_flight:
            self._piezo_operations_in_flight.remove(side)
        self._update_piezo_action(side)
        if self._pending_piezo_operation_close:
            self.alignment_tab.clear_hardware()
            if was_in_flight:
                self._resume_close_after_piezo_operation()
        else:
            self._sync_alignment_hardware()
        return was_in_flight

    def _resume_close_after_piezo_operation(self):
        """Schedule close only after all piezo workers release their controllers."""
        if self._pending_piezo_operation_close and not self._piezo_operations_in_flight:
            QTimer.singleShot(0, self.close)

    @Slot(str, str)
    def _on_ct400_status_updated(self, state_name: str, message: str):
        """Updates the status bar from the CT400 init worker."""
        try:
            state = CT400Status[state_name.upper()]
        except KeyError:
            state = CT400Status.UNKNOWN

        self._update_ct400_visuals(state=state, message=message)

    @Slot(AbstractCT400)
    def _on_ct400_initialized(self, device: AbstractCT400):
        """
        Receives the initialized CT400 device (real or dummy) from the worker.
        This slot is now responsible for populating the rest of the UI
        that depends on the CT400.
        """
        logger.info(f"CT400 initialization finished. Received device: {type(device)}")
        if self._alignment_hardware_transition_blocked() and device is not self.ct400_device:
            logger.warning("Ignoring CT400 replacement while alignment owns the current hardware.")
            if isinstance(device, CT400):
                try:
                    device.close()
                except Exception:
                    logger.exception("Could not release rejected CT400 resources.")
            return
        self.ct400_device = device

        # Now that the device exists, pass it to the control panels
        self.control_panel.set_instrument(self.ct400_device)
        self.histogram_control.set_instrument(self.ct400_device)

        # Update UI visuals based on whether the device is real or dummy
        is_real_ct400 = isinstance(self.ct400_device, CT400)
        is_simulated_ct400 = isinstance(self.ct400_device, DummyCT400)
        # DummyCT400 exposes the same scan interface and is safe to operate in
        # development mode. Keep it unavailable to connection controls, but
        # allow scans and label their results as simulated below.
        self.control_panel.on_instrument_connected(is_real_ct400 or is_simulated_ct400)
        self.histogram_control.on_instrument_connected(is_real_ct400 or is_simulated_ct400)

        if is_real_ct400:
            self._update_ct400_visuals(state=CT400Status.DISCONNECTED, message="CT400 Ready (Disconnected)")
        else:
            # The status was already set to UNAVAILABLE by the worker's error
            pass

        if is_simulated_ct400:
            self.ct400_status_label.setText("CT400: SIMULATED (Dummy)")

        self._sync_alignment_hardware()

    def _begin_lazy_init(self):
        """Starts all slow hardware initializations on background threads."""
        logger.info("Starting lazy initialization of hardware...")

        # 1. Start Piezo discovery (already asynchronous, good)
        # self._init_piezos_lazy()

        # 2. Start CT400 initialization (NOW asynchronous)
        self._init_ct400_lazy()

        # Start the proprietary Vimba system only when a physical camera is
        # explicitly configured. Simulated cameras use the same panel workflow
        # and remain available on driver-free development machines.
        needs_vimba = any(cam.enabled and cam.backend == "vimba" for cam in self.config.cameras.values())
        if needs_vimba:
            self._start_vimbasystem()
            if not self.vmb_instance:
                logger.error("VimbaSystem not active; physical camera initialization will report unavailable.")
        self._init_cameras_lazy()

    def _init_ct400_lazy(self):
        """Initializes the CT400 on a background thread."""
        if self._pending_init_close:
            logger.info("Skipping CT400 initialization while application close is pending.")
            return
        logger.info("Starting lazy initialization of CT400...")
        # 1. Create the worker
        worker = CT400InitWorker(config=self.config)

        # 2. Connect SPECIFIC signals (TaskRunner handles lifecycle signals)
        worker.ct400_initialized.connect(self._on_ct400_initialized)
        worker.status_updated.connect(self._on_ct400_status_updated)

        # TaskRunner owns the worker and thread for this one-shot operation.
        task = TaskRunner(worker)
        self.ct400_task = task
        task.worker_thread.finished.connect(lambda task=task: self._ct400_init_task_finished.emit(task))
        self._track_init_task(task)
        task.start()

    @Slot(object)
    def _on_ct400_init_task_finished(self, task):
        """Clear only the CT400 task whose thread just finished."""
        if self.ct400_task is task:
            self.ct400_task = None

    def _init_piezos_lazy(self):
        """Initializes the Piezo controllers on a background thread."""
        if self._pending_piezo_operation_close:
            logger.info("Skipping piezo initialization while application close is pending.")
            return
        if self._pending_init_close:
            logger.info("Skipping piezo initialization while application close is pending.")
            return
        if self._piezo_operations_in_flight:
            logger.info("Skipping piezo discovery while a piezo connection operation is active.")
            return
        if self._alignment_hardware_transition_blocked():
            logger.info("Skipping piezo discovery while alignment owns the hardware.")
            return
        logger.info("Starting lazy initialization of Piezo controllers...")

        worker = PiezoInitWorker(config=self.config.instruments)

        # Connect specific data signals
        worker.piezos_initialized.connect(self._on_piezos_initialized)
        worker.initialization_failed.connect(self._on_piezo_init_failed)

        # TaskRunner owns the worker and thread for this one-shot operation.
        task = TaskRunner(worker)
        self.piezo_task = task
        task.worker_thread.finished.connect(lambda task=task: self._piezo_init_task_finished.emit(task))
        self._track_init_task(task)
        task.start()

    def _track_init_task(self, task: TaskRunner):
        """Own an initialization task until its thread reaches its final boundary."""
        self._init_tasks.add(task)
        task.worker_thread.finished.connect(lambda task=task: self._init_task_thread_finished.emit(task))

    @Slot(object)
    def _on_init_task_thread_finished(self, task):
        """Release exactly the initialization task whose thread finished."""
        if task not in self._init_tasks:
            return
        self._init_tasks.remove(task)
        if self._pending_init_close and not self._init_tasks:
            logger.info("All initialization tasks finished; resuming deferred application close.")
            QTimer.singleShot(0, self.close)

    @Slot(object)
    def _on_piezo_init_task_finished(self, task):
        """Clear only the piezo task whose thread just finished."""
        if self.piezo_task is task:
            self.piezo_task = None

    def _start_vimbasystem(self):
        """Initializes and enters the main VimbaSystem context.

        This must be done once before any camera operations can occur.
        """
        if self.vmb_instance is not None:
            logger.info("VmbSystem already active.")
            return
        if not VIMBA_AVAILABLE:
            logger.warning("Vimba camera support is not installed; camera initialization is disabled.")
            self.vmb_instance = None
            return
        try:
            logger.info("Attempting to start VmbSystem...")
            self.vmb_instance = VmbSystem.get_instance()
            self.vmb_instance.__enter__()
            logger.info("VmbSystem entered successfully.")
        except VmbSystemError as e:
            logger.error(f"Failed to enter VmbSystem: {e}", exc_info=True)
            self.vmb_instance = None
            QMessageBox.critical(
                self,
                "Vimba System Error",
                f"Could not initialize Vimba API: {e}\nCameras will be unavailable.",
            )
        except Exception as e:
            logger.critical(f"Unexpected error starting VmbSystem: {e}", exc_info=True)
            self.vmb_instance = None
            QMessageBox.critical(
                self,
                "Vimba System Error",
                f"An unexpected error occurred while starting Vimba API: {e}\nCameras will be unavailable.",
            )

    def _cleanup_vimbasystem(self):
        """Exits the VimbaSystem context cleanly."""
        if self.vmb_instance:
            logger.info("Attempting to exit VmbSystem...")
            try:
                self.vmb_instance.__exit__(None, None, None)
                logger.info("VmbSystem exited successfully.")
            except VmbSystemError as e:
                logger.error(f"Failed to exit VmbSystem: {e}", exc_info=True)
            except Exception as e:
                logger.critical(f"Unexpected error exiting VmbSystem: {e}", exc_info=True)
            finally:
                self.vmb_instance = None

    def _load_defaults_from_config(self):
        """Load default values from config into UI elements."""
        logger.debug("Loading UI defaults from configuration...")
        try:
            if hasattr(self, "control_panel") and self.control_panel:
                scan_defaults = self.config.scan_defaults
                self.control_panel.initial_wl.setText(str(scan_defaults.start_wavelength_nm))
                self.control_panel.final_wl.setText(str(scan_defaults.end_wavelength_nm))
                self.control_panel.resolution.setText(str(scan_defaults.resolution_pm))
                self.control_panel.motor_speed.setText(str(scan_defaults.speed_nm_s))
                self.control_panel.laser_power.setText(str(scan_defaults.laser_power))
                power_unit_idx = self.control_panel.power_unit.findText(scan_defaults.power_unit)
                if power_unit_idx != -1:
                    self.control_panel.power_unit.setCurrentIndex(power_unit_idx)
                for i in range(self.control_panel.input_port.count()):
                    if self.control_panel.input_port.itemData(i).value == scan_defaults.input_port:
                        self.control_panel.input_port.setCurrentIndex(i)
                        break

            if hasattr(self, "histogram_control") and self.histogram_control:
                hist_defaults = self.config.histogram_defaults
                self.histogram_control.wavelength_input.setText(str(hist_defaults.wavelength_nm))
                self.histogram_control.laser_power.setText(str(hist_defaults.laser_power))
                power_unit_idx_hist = self.histogram_control.power_unit.findText(hist_defaults.power_unit)
                if power_unit_idx_hist != -1:
                    self.histogram_control.power_unit.setCurrentIndex(power_unit_idx_hist)
                for i in range(self.histogram_control.input_port.count()):
                    if self.histogram_control.input_port.itemData(i).value == hist_defaults.input_port:
                        self.histogram_control.input_port.setCurrentIndex(i)
                        break
                if hasattr(self.histogram_control, "detector_cbs"):
                    for i, checkbox in enumerate(self.histogram_control.detector_cbs):
                        is_enabled = getattr(hist_defaults, f"detector_{i + 1}_enabled", False)
                        checkbox.setChecked(is_enabled)
        except Exception as e:
            logger.error(f"Error loading defaults from config: {e}", exc_info=True)
            self.statusBar.showMessage("Error loading defaults from config", 5000)

    def _init_ui(self):
        """Constructs the main user interface of the application."""
        logger.debug("Initializing UI...")
        self.setWindowTitle(self.config.app_name)
        self.setWindowIcon(QIcon(":/icons/laser.svg"))
        self.setMinimumSize(1200, 800)

        try:
            screen = QApplication.primaryScreen().availableGeometry()
            width_ratio = self.config.ui.initial_width_ratio
            height_ratio = self.config.ui.initial_height_ratio
            self.resize(int(screen.width() * width_ratio), int(screen.height() * height_ratio))
        except Exception as e:
            logger.warning(f"Could not set initial size based on screen: {e}")
            self.resize(1280, 850)

        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QVBoxLayout(central_widget)
        main_layout.setContentsMargins(5, 5, 5, 5)
        main_layout.setSpacing(5)
        splitter = QSplitter(Qt.Orientation.Vertical)
        self.main_splitter = splitter
        splitter.setHandleWidth(6)
        splitter.setChildrenCollapsible(False)
        self.camera_container = QWidget()
        cam_layout = QHBoxLayout(self.camera_container)
        cam_layout.setContentsMargins(0, 0, 0, 0)
        cam_layout.setSpacing(5)
        self.control_container = QWidget()
        control_layout = QVBoxLayout(self.control_container)  # Update variable name usage here too
        control_layout.setContentsMargins(0, 0, 0, 0)
        control_layout.setSpacing(5)
        self.tab_widget = QTabWidget()
        self.tab_widget.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        control_layout.addWidget(self.tab_widget)
        splitter.addWidget(self.camera_container)
        splitter.addWidget(self.control_container)
        initial_cam_height = int(self.height() * 0.6)
        splitter.setSizes([initial_cam_height, self.height() - initial_cam_height])
        main_layout.addWidget(splitter)

        # --- IMPORTANT: Pass None for ct400_device initially ---
        self.first_tab = QWidget()
        first_tab_layout = QHBoxLayout(self.first_tab)
        self.control_panel = CT400ControlPanel(self.shared_scan_settings, None, self.config)
        self.plot_widget = PlotWidget(self.shared_scan_settings, settings=self.settings)
        first_tab_layout.addWidget(self.control_panel, stretch=0)
        first_tab_layout.addWidget(self.plot_widget, stretch=1)
        self.tab_widget.addTab(self.first_tab, "Wavelength Scan")

        self.second_tab = QWidget()
        second_tab_layout = QHBoxLayout(self.second_tab)
        self.histogram_control = HistogramControlPanel(None, self.config)
        hist_detector_keys = [cb.text() for cb in self.histogram_control.detector_cbs]
        self.histogram_widget = HistogramWidget(self.histogram_control, hist_detector_keys)
        second_tab_layout.addWidget(self.histogram_control, stretch=0)
        second_tab_layout.addWidget(self.histogram_widget, stretch=1)
        self.tab_widget.addTab(self.second_tab, "Power Monitor")

        self.alignment_tab = AlignmentPanel(None, None, None, self)
        self.tab_widget.addTab(self.alignment_tab, "Auto Alignment")

        self.setStatusBar(QStatusBar())
        self.ct400_status_label = QLabel("CT400: Initializing...")
        self.ct400_status_label.setObjectName(ID_CT400_STATUS_LABEL)
        self.statusBar().addPermanentWidget(self.ct400_status_label)
        self.statusBar().showMessage("Ready.")

        self._create_menus()

        self._update_ct400_visuals(state=CT400Status.UNKNOWN, message="Initializing...")
        logger.debug("UI Initialization finished.")

    @Slot(object, object)
    def _on_piezos_initialized(self, piezo_left: PiezoController | None, piezo_right: PiezoController | None):
        logger.info("MainWindow: Piezo discovery finished.")
        if self._alignment_hardware_transition_blocked():
            logger.warning("Ignoring piezo discovery results while alignment owns the current hardware.")
            return
        for side, candidate in (("left", piezo_left), ("right", piezo_right)):
            existing = self.piezo_left if side == "left" else self.piezo_right
            if side in self._piezo_operations_in_flight:
                logger.warning("Ignoring %s discovery result while its controller operation is active.", side)
                continue
            if existing is not None and existing.is_connected():
                selected = existing
            else:
                selected = candidate
            if side == "left":
                self.piezo_left = selected
            else:
                self.piezo_right = selected
            self._update_piezo_action(side)
        self._sync_alignment_hardware()

    @Slot()
    def toggle_cinema_mode(self):
        """Toggles the visibility of the bottom control section."""
        is_visible = self.control_container.isVisible()
        self.control_container.setVisible(not is_visible)

        # Optional: Hide the status bar too for a cleaner look
        self.statusBar().setVisible(not is_visible)

        logger.debug(f"Cinema Mode {'Enabled' if is_visible else 'Disabled'}")

    @Slot(str)
    def _on_piezo_init_failed(self, error_message: str):
        logger.error(f"Piezo initialization failed: {error_message}")
        QMessageBox.critical(
            self,
            "Piezo Error",
            f"Could not initialize Piezo controllers:\n{error_message}\n\nAlignment tab will be unavailable.",
        )
        self._update_piezo_action("left")
        self._update_piezo_action("right")
        self._sync_alignment_hardware()

    def _update_ct400_visuals(self, state: CT400Status, message: str | None = None):
        """Updates all UI elements related to the CT400 connection status.

        This centralizes the logic for updating the menu action, status bar label,
        and main status message based on the device's state.

        Args:
            state: The new CT400Status to reflect in the UI.
            message: An optional message to display in the status bar.
        """
        action = getattr(self, "ct400_connect_action", None)
        label = getattr(self, "ct400_status_label", None)
        if not action or not label:
            return

        action_enabled, action_checked = True, False
        status_property = state.name.lower()

        state_map = {
            CT400Status.CONNECTED: ("Disconnect CT400", ":/icons/disconnect.svg", True, True),
            CT400Status.DISCONNECTED: ("Connect CT400", ":/icons/connect.svg", True, False),
            CT400Status.CONNECTING: ("Connecting...", ":/icons/spinner.svg", False, True),
            CT400Status.DISCONNECTING: ("Disconnecting...", ":/icons/spinner.svg", False, False),
            CT400Status.ERROR: ("Connect CT400 (Error)", ":/icons/connect.svg", True, False),
            CT400Status.UNAVAILABLE: ("CT400 Unavailable", ":/icons/laser.svg", False, False),
            CT400Status.UNKNOWN: ("CT400 Initializing", ":/icons/spinner.svg", False, False),
        }

        text, icon, action_enabled, action_checked = state_map[state]
        action.setText(text)
        action.setIcon(QIcon(icon))
        self._ct400_visual_state = state
        action.setEnabled(
            action_enabled
            and isinstance(self.ct400_device, CT400)
            and self._ct400_operation_state is CT400OperationState.IDLE
        )
        action.setChecked(action_checked)

        label.setText(f"CT400: {state.name.replace('_', ' ').title()}")
        label.setProperty(PROP_STATUS, status_property)
        label.style().unpolish(label)
        label.style().polish(label)

        if message:
            timeout = 5000 if state in [CT400Status.CONNECTED, CT400Status.DISCONNECTED, CT400Status.ERROR] else 0
            self.statusBar().showMessage(message, timeout)

        if state == CT400Status.ERROR:
            self._ct400_error_reset_timer.start(3000)
        elif self._ct400_error_reset_timer.isActive():
            self._ct400_error_reset_timer.stop()

        self.is_ct400_connected_state = state == CT400Status.CONNECTED

    @Slot()
    def _reset_ct400_error_visuals(self):
        """Return an error status to disconnected while owned by this window."""
        self._update_ct400_visuals(CT400Status.DISCONNECTED, "Error occurred. Ready to connect.")

    def _create_menus(self):
        """Creates the main menu bar and all its actions."""
        logger.debug("Creating menus...")
        menu_bar = self.menuBar()

        file_menu = menu_bar.addMenu("&File")
        exit_action = QAction(QIcon(":/icons/exit.svg"), "E&xit", self)
        exit_action.setStatusTip("Exit the application")
        exit_action.triggered.connect(self.close)
        file_menu.addAction(exit_action)

        self.instrument_menu = menu_bar.addMenu("&Instruments")
        # --- NEW: Refresh Action ---
        refresh_action = QAction(QIcon(":/icons/refresh.svg"), "Refresh Instruments", self)
        refresh_action.setStatusTip("Scan for newly connected CT400 or Piezo devices")
        refresh_action.triggered.connect(self._on_refresh_instruments_triggered)
        self.instrument_menu.addAction(refresh_action)
        self.instrument_menu.addSeparator()
        # ---------------------------
        self.ct400_connect_action = QAction(self)
        self.ct400_connect_action.setCheckable(True)
        self.ct400_connect_action.setStatusTip("Connect/Disconnect CT400 device")
        self.ct400_connect_action.triggered.connect(self._handle_ct400_connect_action_triggered)
        self.instrument_menu.addAction(self.ct400_connect_action)

        self.cameras_menu = menu_bar.addMenu("&Cameras")
        discover_action = QAction("Discover Cameras...", self)
        discover_action.setStatusTip("List all available Vimba cameras and their IDs")
        discover_action.triggered.connect(self._show_camera_discovery_dialog)
        self.cameras_menu.addSeparator()
        self.cameras_menu.addAction(discover_action)
        self.cameras_menu.addSeparator()  # Add another separator for neatness

        self.piezo_connect_left_action = QAction("Connect Left Piezo", self)
        self.piezo_connect_left_action.triggered.connect(lambda: self.connect_piezo("left"))
        self.instrument_menu.addAction(self.piezo_connect_left_action)

        self.piezo_connect_right_action = QAction("Connect Right Piezo", self)
        self.piezo_connect_right_action.triggered.connect(lambda: self.connect_piezo("right"))
        self.instrument_menu.addAction(self.piezo_connect_right_action)
        self._update_piezo_action("left")
        self._update_piezo_action("right")

        help_menu = menu_bar.addMenu("&Help")
        about_action = QAction("&About", self)
        about_action.setStatusTip("Show application information")
        about_action.triggered.connect(self._show_about_dialog)
        help_menu.addAction(about_action)
        logger.debug("Menus created.")

    @Slot()
    def _on_refresh_instruments_triggered(self):
        """
        Manually triggers discovery for Piezos and CT400.
        Useful if instruments were turned on after the GUI started.
        """
        logger.info("Manual Instrument Refresh requested.")
        if self._pending_init_close:
            logger.info("Ignoring instrument refresh while application close is pending.")
            return
        if self._pending_piezo_operation_close:
            logger.info("Ignoring instrument refresh while piezo operation shutdown is pending.")
            return
        if self._alignment_hardware_transition_blocked():
            self.statusBar().showMessage("Stop alignment before refreshing instruments.", 5000)
            return
        self.statusBar().showMessage("Scanning for instruments...", 3000)

        # 1. Refresh Piezos
        # We always try to find piezos if requested, unless a scan is already running.
        piezo_task = self.piezo_task
        if self._piezo_operations_in_flight:
            logger.info("Skipping piezo discovery while a piezo connection operation is active.")
        elif piezo_task is not None and piezo_task.worker_thread.isRunning():
            logger.info("Piezo discovery already running. Skipping.")
        else:
            self._init_piezos_lazy()

        # 2. Refresh CT400
        # Only try to re-initialize CT400 if we are currently using a Dummy device
        # or if no device is set. We don't want to kill a live connection.
        is_dummy = isinstance(self.ct400_device, DummyCT400)
        is_none = self.ct400_device is None

        if is_dummy or is_none:
            ct400_task = self.ct400_task
            if ct400_task is not None and ct400_task.worker_thread.isRunning():
                logger.info("CT400 init already running. Skipping.")
            else:
                logger.info("Current CT400 is Dummy/None. Re-scanning for real hardware...")
                self._update_ct400_visuals(state=CT400Status.UNKNOWN, message="Searching for CT400...")

                self._init_ct400_lazy()
        else:
            logger.info("CT400 is already connected to real hardware. Skipping refresh.")
            self.statusBar().showMessage("CT400 connected. Scanning Piezos only...", 3000)

    @Slot()
    def _show_camera_discovery_dialog(self):
        """Shows the camera discovery dialog.

        Ensures the Vimba system is running before creating and executing the
        modal dialog to discover connected cameras.
        """
        if self.vmb_instance is None:
            QMessageBox.warning(
                self,
                "Vimba System Not Ready",
                "The Vimba API has not been initialized. Cannot discover cameras.\n"
                "Please ensure the Vimba SDK is installed correctly.",
            )
            return

        try:
            dialog = CameraDiscoveryDialog(self)
            dialog.exec()
        except Exception as e:
            logger.error(f"Failed to create or show camera discovery dialog: {e}", exc_info=True)
            QMessageBox.critical(self, "Dialog Error", f"Could not open the discovery dialog: {e}")

    @Slot(bool)
    def _handle_ct400_connect_action_triggered(self, checked: bool):
        """Handles the CT400 connect/disconnect menu action.

        Starts a CT400ConnectionWorker on the global thread pool to perform
        the hardware operation without blocking the GUI. Updates the UI to
        reflect the connecting/disconnecting state.

        Args:
            checked: True if the action is toggled to a "checked" state (connect),
                     False otherwise (disconnect).
        """
        action = self.sender()
        if action:
            action.setEnabled(False)  # Prevent rapid re-clicks

        if not self.ct400_device or isinstance(self.ct400_device, DummyCT400):
            self._update_ct400_visuals(state=CT400Status.UNAVAILABLE, message="CT400 Not Initialized or Dummy.")
            if action:
                action.setChecked(False)
                action.setEnabled(True)
            return

        if self._ct400_operation_state is not CT400OperationState.IDLE:
            logger.warning("Ignoring CT400 Connect/Disconnect request while an operation is active.")
            if action:
                action.setChecked(self.is_ct400_connected_state)
                action.setEnabled(False)
            return

        worker = CT400ConnectionWorker(self.ct400_device, self.config, connect=checked)
        worker.signals.connection_succeeded.connect(self._handle_ct400_connection_success)
        worker.signals.connection_failed.connect(self._handle_ct400_connection_failure)
        worker.signals.disconnection_succeeded.connect(self._handle_ct400_disconnection_success)
        worker.signals.disconnection_failed.connect(self._handle_ct400_connection_failure)
        worker.signals.finished.connect(self._handle_ct400_connection_operation_finished)

        self._set_ct400_operation_state(
            CT400OperationState.CONNECTING if checked else CT400OperationState.DISCONNECTING
        )
        if checked:
            self._update_ct400_visuals(state=CT400Status.CONNECTING, message="CT400: Attempting to connect...")
        else:
            self._update_ct400_visuals(state=CT400Status.DISCONNECTING, message="CT400: Disconnecting...")

        QThreadPool.globalInstance().start(worker)

    def _set_ct400_operation_state(self, state: CT400OperationState):
        self._ct400_operation_state = state
        if hasattr(self, "control_panel") and self.control_panel:
            self.control_panel.set_ct400_operation_state(state.name)
        if hasattr(self, "histogram_control") and self.histogram_control:
            self.histogram_control.set_ct400_operation_state(state.name)
        if hasattr(self, "alignment_tab") and self.alignment_tab:
            self.alignment_tab.set_ct400_operation_state(state.name)
        action = getattr(self, "ct400_connect_action", None)
        if action is not None:
            if state is CT400OperationState.IDLE:
                status = getattr(self, "_ct400_visual_state", CT400Status.DISCONNECTED)
                enabled = status in (CT400Status.CONNECTED, CT400Status.DISCONNECTED, CT400Status.ERROR)
                action.setEnabled(enabled and isinstance(self.ct400_device, CT400))
            else:
                action.setEnabled(False)

    @Slot()
    def _handle_ct400_scan_started(self):
        if self._ct400_operation_state is CT400OperationState.IDLE:
            self._set_ct400_operation_state(CT400OperationState.SCANNING)

    @Slot()
    def _handle_ct400_scan_finished(self):
        if self._ct400_operation_state is CT400OperationState.SCANNING:
            self._set_ct400_operation_state(CT400OperationState.IDLE)

    @Slot()
    def _handle_ct400_monitor_started(self):
        if self._ct400_operation_state is CT400OperationState.IDLE:
            self._set_ct400_operation_state(CT400OperationState.MONITORING)

    @Slot()
    def _handle_ct400_monitor_finished(self):
        if self._ct400_operation_state is CT400OperationState.MONITORING:
            self._set_ct400_operation_state(CT400OperationState.IDLE)
        self._resume_close_after_ct400_operation()

    @Slot()
    def _handle_alignment_operation_started(self):
        if self._ct400_operation_state is CT400OperationState.IDLE:
            self._set_ct400_operation_state(CT400OperationState.ALIGNMENT)
        else:
            logger.error("Rejected alignment start while CT400 is owned by %s", self._ct400_operation_state.name)

    @Slot()
    def _handle_alignment_operation_finished(self):
        if self._ct400_operation_state is CT400OperationState.ALIGNMENT:
            self._set_ct400_operation_state(CT400OperationState.IDLE)
        self._resume_close_after_ct400_operation()

    def _resume_close_after_ct400_operation(self):
        if self._pending_ct400_operation_close and self._ct400_operation_state is CT400OperationState.IDLE:
            self._pending_ct400_operation_close = False
            QTimer.singleShot(0, self.close)

    @Slot()
    def _handle_ct400_connection_operation_finished(self):
        """Release connection-operation ownership and resume deferred shutdown."""
        if self._ct400_operation_state in (CT400OperationState.CONNECTING, CT400OperationState.DISCONNECTING):
            self._set_ct400_operation_state(CT400OperationState.IDLE)
        action = getattr(self, "ct400_connect_action", None)
        if action is not None:
            action.setEnabled(True)

        self._resume_close_after_ct400_operation()

    @Slot(str)
    def _handle_ct400_connection_success(self, message: str):
        """Slot to handle a successful CT400 connection."""
        self._ct400_connection_configured = True
        self._update_ct400_visuals(state=CT400Status.CONNECTED, message=message)
        self.control_panel.on_instrument_connected(True)
        self.histogram_control.on_instrument_connected(True)

    @Slot(str)
    def _handle_ct400_connection_failure(self, error_message: str):
        """Slot to handle a failed CT400 connection or disconnection."""
        self._update_ct400_visuals(state=CT400Status.ERROR, message=error_message)
        self.control_panel.on_instrument_connected(False)
        self.histogram_control.on_instrument_connected(False)

    @Slot(str)
    def _handle_ct400_disconnection_success(self, message: str):
        """Slot to handle a successful CT400 disconnection."""
        self._ct400_connection_configured = False
        self._update_ct400_visuals(state=CT400Status.DISCONNECTED, message=message)
        self.control_panel.on_instrument_connected(False)
        self.histogram_control.on_instrument_connected(False)

    def _show_about_dialog(self):
        """Displays the 'About' message box with application info."""
        app_name = self.config.app_name
        app_version = QApplication.applicationVersion()
        QMessageBox.about(
            self,
            f"About {app_name}",
            f"<b>{app_name}</b><br>"
            f"Version: {app_version}<br><br>"
            "IOPanel App.<br>"
            "(c) 2025 Simone Ferraresi/IOP Lab @ UniFe",
        )

    def _init_cameras_lazy(self):
        """Initializes all enabled cameras asynchronously.

        For each valid camera in the config, this method creates a placeholder
        UI panel, then spawns a dedicated worker thread (CameraInitWorker) to
        open the camera. This prevents the UI from freezing while waiting for
        multiple cameras to connect.
        """
        logger.info("Initializing cameras lazily...")
        if not all([self.camera_container, self.camera_container.layout(), self.cameras_menu]):
            logger.error("UI components for camera initialization are not ready. Aborting.")
            return

        # Get a dictionary of valid camera configs, keyed by their identifier.
        camera_configs_to_init = {
            identifier: config
            for identifier, config in self.config.cameras.items()
            if self._should_initialize_camera(identifier, config)
        }

        if not camera_configs_to_init:
            no_cameras_action = QAction("No enabled cameras found in config", self)
            no_cameras_action.setEnabled(False)
            self.cameras_menu.addAction(no_cameras_action)
            logger.info("No valid, enabled cameras to initialize.")
            return

        for identifier, config in camera_configs_to_init.items():
            logger.debug(f"Setting up initialization for camera '{config.name}' (ID: {identifier})")

            # 1. Create and add the placeholder panel to the UI
            placeholder_panel = self._create_camera_panel(None, config)
            self.camera_panels[identifier] = placeholder_panel
            self.camera_container.layout().addWidget(placeholder_panel)

            # Create Worker
            worker = CameraInitWorker(identifier=identifier, cam_config=config)
            worker.camera_initialized.connect(self._on_camera_initialized)

            # Create Runner
            task = TaskRunner(worker)

            self._track_init_task(task)
            task.start()

    @Slot(str, object, CameraConfig)
    def _on_camera_initialized(self, identifier: str, camera_instance: VimbaCam | None, cam_config: CameraConfig):
        """Slot to handle a camera that has finished initializing.

        This method is called when a `CameraInitWorker` finishes. If the camera
        was initialized successfully, it connects the camera's signals to the
        UI panel, adds it to the list of active cameras, and creates a menu
        action for it. If it failed, it updates the panel to show an error state.

        Args:
            identifier: The unique ID of the camera that was initialized.
            camera_instance: The live `VimbaCam` object if successful, else `None`.
            cam_config: The configuration object for the camera.
        """
        panel = self.camera_panels.get(identifier)  # Find panel by identifier
        if not panel:
            logger.error(f"Could not find panel for camera config: {cam_config.name}")
            if camera_instance:
                camera_instance.close()
            return

        if isinstance(camera_instance, SimulatedCamera) and not camera_instance.open():
            camera_instance.close()
            camera_instance = None

        if camera_instance:
            logger.info(f"Camera '{cam_config.name}' is online. Connecting to UI.")
            self.cameras.append(camera_instance)

            panel.set_camera(camera_instance)
            self._connect_camera_signals(camera_instance, panel)
            self._create_camera_menu_action(camera_instance, panel)
            panel._arm_watchdog()

            panel.video_label.setText(MSG_CAMERA_WAITING)
        else:
            logger.error(f"Failed to initialize camera '{cam_config.name}'.")
            error_msg = f"{cam_config.name}\n(Failed to Open)"
            panel.video_label.setText(error_msg)
            panel.video_label.setStyleSheet("background-color: #ffebee; color: #c62828;")

    def _should_initialize_camera(self, identifier: str, cam_config: CameraConfig) -> bool:
        """Checks if a camera from the config should be initialized."""
        if not cam_config.enabled:
            logger.info(f"Skipping disabled camera: {cam_config.name}")
            return False
        if not identifier or identifier.startswith("PUT_"):
            logger.warning(f"Skipping camera '{cam_config.name}': Invalid or placeholder identifier.")
            error_msg = f"{cam_config.name}\n(Config Error: Invalid ID)"
            placeholder = self._create_camera_error_placeholder(error_msg)
            self.camera_container.layout().addWidget(placeholder)
            return False
        return True

    def _create_and_open_camera(self, cam_config: CameraConfig) -> VimbaCam | None:
        """Creates a VimbaCam instance and attempts to open it. Returns instance or None."""
        try:
            cam_instance = VimbaCam(
                identifier=cam_config.identifier,
                camera_name=cam_config.name,
                flip_horizontal=cam_config.flip_horizontal,
                parent=self,
            )
            if not cam_instance.open():
                logger.error(f"Failed to open camera {cam_config.name} (ID: {cam_config.identifier}).")
                error_msg = MSG_CAMERA_FAILED.format(cam_config.name)
                placeholder = self._create_camera_error_placeholder(error_msg)
                self.camera_container.layout().addWidget(placeholder)
                cam_instance.close()  # Clean up the failed instance
                return None
            return cam_instance
        except VmbCameraError as e:
            logger.error(f"Vimba Error initializing camera {cam_config.name} (ID: {cam_config.identifier}): {e}")
            error_msg = f"{cam_config.name}\n(Vimba Error)"
            placeholder = self._create_camera_error_placeholder(error_msg)
            self.camera_container.layout().addWidget(placeholder)
            return None
        except Exception as e:
            logger.error(
                f"Unexpected error creating camera instance {cam_config.name}: {e}",
                exc_info=True,
            )
            error_msg = f"{cam_config.name}\n(Init Error)"
            placeholder = self._create_camera_error_placeholder(error_msg)
            self.camera_container.layout().addWidget(placeholder)
            return None

    def _create_camera_panel(self, cam_instance: VimbaCam | None, cam_config: CameraConfig) -> CameraPanel:
        title = f"{cam_config.name} [SIMULATED]" if cam_config.backend == "simulation" else cam_config.name
        panel = CameraPanel(
            cam_instance,
            title,
            config=cam_config,
            parent=self.camera_container,
            settings=self.settings,
        )
        panel.set_controls_visibility(self.settings.camera_controls_visible(cam_config.identifier))
        if not cam_instance:
            panel.video_label.setText(MSG_CAMERA_CONNECTING.format(cam_config.name))

        # --- NEW: Connect double-click signal ---
        panel.maximize_requested.connect(self.toggle_cinema_mode)
        # ----------------------------------------

        return panel

    def _connect_camera_signals(self, cam_instance: VimbaCam, panel: CameraPanel):
        """Connects signals between a camera instance and its UI panel."""
        # The connection to the worker is now handled inside CameraPanel.
        # We only need to connect the signals that the panel itself consumes.

        # This connection is now just for the watchdog timer
        cam_instance.new_frame.connect(panel.process_new_frame_data)

        cam_instance.fps_updated.connect(panel.update_fps)
        cam_instance.error.connect(panel._handle_camera_error_message)
        panel.recovery_requested.connect(self._request_camera_recovery)
        panel.auto_operation_finished.connect(self._on_camera_auto_operation_finished)

    @Slot(str)
    def _request_camera_recovery(self, identifier: str):
        """Own at most one recovery TaskRunner per camera identifier."""
        if identifier in self._camera_recovery_tasks or self._pending_camera_lifecycle_close:
            return
        camera = next((candidate for candidate in self.cameras if candidate.identifier == identifier), None)
        panel = self.camera_panels.get(identifier)
        if camera is None or panel is None:
            return

        worker = CameraRecoveryWorker(camera, identifier)
        task = TaskRunner(worker)
        self._camera_recovery_tasks[identifier] = task
        worker.task = task
        worker.recovery_finished.connect(self._on_camera_recovery_result)
        task.worker_thread.finished.connect(
            lambda camera_id=identifier, task=task: self._camera_recovery_thread_finished.emit(camera_id, task)
        )
        task.start()

    @Slot(str, bool, str, object)
    def _on_camera_recovery_result(self, identifier: str, success: bool, message: str, task: TaskRunner):
        current_task = self._camera_recovery_tasks.get(identifier)
        if current_task is not None and current_task is not task:
            return
        panel = self.camera_panels.get(identifier)
        if panel is None:
            return
        if success:
            panel.recovery_succeeded()
        else:
            panel.recovery_failed(message)

    def _on_camera_recovery_thread_finished(self, identifier: str, task: TaskRunner):
        """Release ownership only at the exact QThread.finished boundary."""
        if self._camera_recovery_tasks.get(identifier) is task:
            del self._camera_recovery_tasks[identifier]
        self._resume_close_after_camera_lifecycle_if_ready()

    @Slot()
    def _on_camera_auto_operation_finished(self):
        self._resume_close_after_camera_lifecycle_if_ready()

    def _camera_lifecycle_busy(self) -> bool:
        return bool(self._camera_recovery_tasks) or any(
            panel.auto_operation_active for panel in self.camera_panels.values()
        )

    def _resume_close_after_camera_lifecycle_if_ready(self):
        if self._pending_camera_lifecycle_close and not self._camera_lifecycle_busy():
            QTimer.singleShot(0, self.close)

    def _create_camera_menu_action(self, cam_instance: VimbaCam, panel: CameraPanel):
        """Creates and registers a menu action to control the camera panel's visibility."""
        action = QAction(self)
        action.setCheckable(True)
        action.setChecked(panel.get_controls_visible())
        action.setText(f"{'Hide' if panel.get_controls_visible() else 'Show'} {cam_instance.camera_name} Controls")
        action.setData(cam_instance.identifier)
        action.triggered.connect(self._handle_camera_control_toggle)
        self.cameras_menu.addAction(action)
        self.camera_control_actions[cam_instance.identifier] = action

    def _create_camera_error_placeholder(self, message: str) -> QWidget:
        """Helper to create a consistent placeholder for camera errors."""
        placeholder_widget = QFrame()
        placeholder_widget.setObjectName("cameraErrorPlaceholder")
        placeholder_widget.setStyleSheet(
            "QFrame#cameraErrorPlaceholder {"
            "  border: 1px solid #ffcdd2;"
            "  border-radius: 5px;"
            "  background-color: #ffebee;"
            "}"
            "QLabel { color: #c62828; font-weight: normal; background: transparent; }"
        )
        placeholder_widget.setMinimumSize(220, 120)
        placeholder_widget.setMaximumWidth(350)
        placeholder_widget.setSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)

        layout = QVBoxLayout(placeholder_widget)
        layout.setContentsMargins(10, 10, 10, 10)
        layout.setSpacing(5)

        icon_label = QLabel()
        try:
            std_icon = self.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_MessageBoxWarning)
            if not std_icon.isNull():
                icon_label.setPixmap(std_icon.pixmap(QSize(32, 32)))
        except Exception as e_icon:
            logger.warning(f"Could not load standard warning icon: {e_icon}")
            icon_label.setText("⚠️")
            icon_label.setFont(QFont("Segoe UI Symbol", 20))

        icon_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        text_label = QLabel(message)
        text_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        text_label.setWordWrap(True)

        layout.addWidget(icon_label)
        layout.addWidget(text_label)

        placeholder_widget.setToolTip(f"Camera Initialization Error: {message.replace('\n', ' ')}")
        return placeholder_widget

    @Slot(bool)
    def _handle_camera_control_toggle(self, checked: bool):
        action = self.sender()
        if not isinstance(action, QAction):
            return

        camera_identifier = action.data()
        if camera_identifier in self.camera_panels:
            panel = self.camera_panels[camera_identifier]
            panel.set_controls_visibility(checked)
            self.settings.set_camera_controls_visible(camera_identifier, checked)
            action.setText(f"{'Hide' if checked else 'Show'} {panel._panel_title} Controls")
        else:
            logger.warning(f"Camera panel not found for identifier: {camera_identifier} during toggle.")
            action.setChecked(not checked)
            action.setEnabled(False)

    @Slot(object)
    def _handle_scan_data(self, measurement):
        logger.debug(f"Received scan measurement. Wavelength points: {len(measurement.wavelengths_nm)}")

        if self.plot_widget and hasattr(self.plot_widget, "set_measurement"):
            try:
                self.plot_widget.set_measurement(measurement)
                if isinstance(self.ct400_device, DummyCT400):
                    self.plot_widget.plot_widget.setTitle("SIMULATED CT400 DATA", color="darkorange", size="11pt")
            except Exception as e:
                logger.error(f"Error updating plot widget: {e}", exc_info=True)

    @Slot(dict)
    def handle_power_data(self, power_data: dict):
        logger.debug(f"Received power data: {power_data}")
        if self.histogram_widget and hasattr(self.histogram_widget, "schedule_update"):
            try:
                self.histogram_widget.schedule_update(power_data)
            except Exception as e:
                logger.error(f"Error updating histogram widget: {e}", exc_info=True)
        else:
            logger.warning("Histogram widget not available or does not have schedule_update method.")

    def _cleanup_cameras(self):
        logger.info(f"Closing {len(self.cameras)} camera(s)...")

        # Disconnect menu actions
        if hasattr(self, "cameras_menu") and self.cameras_menu is not None:
            for cam_id in list(self.camera_control_actions.keys()):
                action = self.camera_control_actions.pop(cam_id, None)
                if action:
                    self.cameras_menu.removeAction(action)
                    action.deleteLater()
        self.camera_control_actions.clear()

        # Remove panels from the UI
        if hasattr(self, "camera_container") and self.camera_container.layout() is not None:
            layout = self.camera_container.layout()
            while layout.count():
                item = layout.takeAt(0)
                widget = item.widget()
                if widget is not None:
                    # This ensures the panel's own closeEvent is called if it has one
                    widget.close()
                    widget.deleteLater()

        # Close the actual camera hardware instances
        cameras_to_close = list(self.cameras)
        self.cameras.clear()
        self.camera_panels.clear()

        for cam in cameras_to_close:
            if cam is not None:
                logger.debug(f"Closing camera: {cam.camera_name}")
                try:
                    # The camera's close() method handles stopping streaming etc.
                    cam.close()
                except Exception as e:
                    logger.error(f"Error closing camera {cam.camera_name}: {e}", exc_info=True)

        logger.info("Camera cleanup finished.")

    def _disable_configured_ct400_input_for_shutdown(self) -> bool:
        """Apply the connection-level selected-input cleanup before close."""
        laser_input = LaserInput(self.config.scan_defaults.input_port)
        try:
            self.ct400_device.cmd_laser(
                laser_input=laser_input,
                enable=Enable.DISABLE,
                wavelength=self.config.scan_defaults.safe_parking_wavelength,
                power=self.config.scan_defaults.laser_power,
            )
            logger.info("Shutdown disabled configured CT400 input %s.", laser_input.name)
            return True
        except Exception as exc:
            logger.error(
                "Shutdown laser disable could not be confirmed for configured input %s: %s",
                laser_input.name,
                exc,
                exc_info=True,
            )
            QMessageBox.warning(
                self,
                "Laser Disable Not Confirmed",
                f"Laser disable could not be confirmed for configured input {laser_input.name}.\n\n"
                "The application will continue resource cleanup. CT400 native resource close is a separate "
                "operation.\n\n"
                f"{exc}",
            )
            return False

    def closeEvent(self, event: QtGui.QCloseEvent):
        """
        Handles the user closing the window. Ensures all hardware and threads
        are shut down gracefully. This is the single source of truth for cleanup.
        """
        logger.info("Application close requested. Initiating shutdown sequence...")
        scan_panel = getattr(self, "control_panel", None)
        scan_thread = getattr(scan_panel, "scan_thread", None)
        try:
            scan_active = scan_thread is not None and scan_thread.isRunning()
        except RuntimeError:
            scan_active = False
        if scan_active:
            event.ignore()
            self.statusBar().showMessage("Stopping/waiting for CT400 scan to finish…", 0)
            logger.info("Deferring application close until the active CT400 scan worker finishes.")
            self._pending_scan_close = True
            if not getattr(self, "_close_resume_connected", False):
                self._close_resume_connected = True
                scan_thread.finished.connect(self._resume_close_after_scan)
            scan_panel._stop_scan(cancelled=True)
            if not scan_thread.isRunning():
                self._resume_close_after_scan()
            return

        if self._camera_lifecycle_busy():
            event.ignore()
            self._pending_camera_lifecycle_close = True
            self.statusBar().showMessage("Waiting for camera operation to finish…", 0)
            logger.info("Deferring application close until camera recovery/auto operations finish.")
            return

        if self._ct400_operation_state in (CT400OperationState.CONNECTING, CT400OperationState.DISCONNECTING):
            event.ignore()
            self._pending_ct400_operation_close = True
            self.statusBar().showMessage("Waiting for CT400 connection operation to finish…", 0)
            logger.info("Deferring application close until the CT400 Connect/Disconnect operation finishes.")
            return

        if self._ct400_operation_state is CT400OperationState.MONITORING:
            event.ignore()
            self._pending_ct400_operation_close = True
            self.statusBar().showMessage("Stopping power monitoring before CT400 shutdown…", 0)
            self.histogram_control._stop_monitoring()
            return

        if self._ct400_operation_state is CT400OperationState.ALIGNMENT:
            event.ignore()
            self._pending_ct400_operation_close = True
            self.statusBar().showMessage("Stopping/waiting for alignment CT400 cleanup…", 0)
            logger.info("Deferring application close until alignment laser cleanup completes.")
            self.alignment_tab.request_stop()
            return

        if self._init_tasks:
            event.ignore()
            self._pending_init_close = True
            self.statusBar().showMessage("Waiting for hardware initialization to finish…", 0)
            logger.info("Deferring application close with %d initialization task(s) active.", len(self._init_tasks))
            return

        if self._piezo_operations_in_flight:
            event.ignore()
            self._pending_piezo_operation_close = True
            active_sides = ", ".join(sorted(self._piezo_operations_in_flight))
            self.statusBar().showMessage("Waiting for piezo operation to finish…", 0)
            logger.info("Deferring application close while piezo operation(s) remain active: %s", active_sides)
            return

        self.statusBar().showMessage("Shutting down...", 0)

        # Capture the final harmless UI snapshot before camera cleanup clears
        # the panel registry used to read camera control visibility.
        self._save_ui_preferences()

        # Cleanup long-running panel workers
        if hasattr(self, "alignment_tab") and self.alignment_tab:
            self.alignment_tab.cleanup()

        if hasattr(self, "histogram_control") and self.histogram_control:
            self.histogram_control.cleanup_worker_thread()

        # 2. Close all camera streams
        self._cleanup_cameras()

        # 3. Disconnect from physical hardware
        try:
            if self.piezo_left and self.piezo_left.is_connected():
                self.piezo_left.disconnect()
            if self.piezo_right and self.piezo_right.is_connected():
                self.piezo_right.disconnect()

        except Exception as e:
            logger.error(f"Error disconnecting piezo hardware: {e}")

        # Stop monitoring above so its own selected input is handled before
        # releasing the CT400. A successful GUI disconnect already disabled
        # the configured input. Retain that knowledge separately from the UI
        # connection flag so an error-state disconnect is retried at shutdown.
        device = self.ct400_device
        if isinstance(device, CT400):
            if self.is_ct400_connected_state or self._ct400_connection_configured:
                self._disable_configured_ct400_input_for_shutdown()
            if device.handle is not None:
                logger.info("MainWindow.closeEvent: Releasing initialized CT400 resources.")
                try:
                    device.close()
                except Exception as exc:
                    logger.error("CT400 native resource close failed: %s", exc, exc_info=True)
                    QMessageBox.warning(
                        self,
                        "CT400 Resource Close Failed",
                        f"CT400 native resource close failed:\n\n{exc}",
                    )
        elif isinstance(device, DummyCT400) and self.is_ct400_connected_state:
            # Retain the existing simulation close path; never treat the dummy
            # as a native handle owner or send configured physical commands.
            logger.info("MainWindow.closeEvent: Closing connected DummyCT400 simulation.")
            device.close()

        # 4. Shut down the main Vimba system API
        self._cleanup_vimbasystem()

        logger.info("Shutdown complete.")
        self._pending_init_close = False
        self._pending_camera_lifecycle_close = False
        self._pending_piezo_operation_close = False
        event.accept()

    def _save_ui_preferences(self) -> None:
        """Save only presentation state and the selected scan detector IDs."""
        if not self.isFullScreen():
            self.settings.set_geometry(self.saveGeometry())
        if self.control_container.isVisible():
            self.settings.set_splitter_sizes(self.main_splitter.sizes())
        self.settings.set_active_tab(self.tab_widget.currentIndex())
        self.settings.set_scan_detectors(
            [detector.value for detector in self.control_panel._selected_scan_detectors()]
        )
        for camera_id, panel in self.camera_panels.items():
            self.settings.set_camera_controls_visible(camera_id, panel.get_controls_visible())
        self.settings.sync()

    @Slot()
    def _resume_close_after_scan(self):
        """Resume a deferred close on the GUI thread after scan cleanup."""
        if getattr(self, "_pending_scan_close", False):
            self._pending_scan_close = False
            QTimer.singleShot(0, self.close)

    def _connect_signals(self):
        """Connects signals between different components of the application."""
        if hasattr(self, "control_panel") and self.control_panel:
            logger.debug("Connecting control_panel signals")
            self.control_panel.scan_data_ready.connect(self._handle_scan_data)
            self.control_panel.operation_started.connect(self._handle_ct400_scan_started)
            self.control_panel.operation_finished.connect(self._handle_ct400_scan_finished)
            self.control_panel.scan_warning.connect(lambda message: self.statusBar().showMessage(message, 10000))
        else:
            logger.warning("CT400 Control Panel not initialized, skipping signal connection.")

        if hasattr(self, "histogram_control") and self.histogram_control:
            logger.debug("Connecting histogram_control signals")
            self.histogram_control.power_data_ready.connect(self.handle_power_data)
            self.histogram_control.operation_started.connect(self._handle_ct400_monitor_started)
            self.histogram_control.operation_finished.connect(self._handle_ct400_monitor_finished)
        else:
            logger.warning("Histogram Control Panel not initialized, skipping signal connection.")

        if hasattr(self, "alignment_tab") and self.alignment_tab:
            self.alignment_tab.operation_started.connect(self._handle_alignment_operation_started)
            self.alignment_tab.operation_finished.connect(self._handle_alignment_operation_finished)
